[package]
name = "cxx-qt-lib-additions"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = { workspace = true }
cxx-qt = { workspace = true }

[build-dependencies]
cxx-qt-build = { workspace = true }


