[package]
name = "chameleon_settings"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = {workspace = true}
serde = {workspace = true}
log = "0.4.28"
clap = { version = "4.5.48", features = ["derive"] }


